# Generated by Django 4.0.4 on 2022-04-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comments_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='name',
            new_name='title',
        ),
    ]
