# Generated by Django 4.0.4 on 2022-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_name_auction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='url_link',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
