# Generated by Django 4.0.4 on 2022-05-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_watchlist_alter_auction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watchlist',
        ),
    ]
