# Generated by Django 4.0.4 on 2022-05-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
