# Generated by Django 4.0.4 on 2022-05-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlists'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlists',
            unique_together={('watcher', 'auction')},
        ),
    ]
