# Generated by Django 4.0.4 on 2022-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlists_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[(1, 'Open'), (0, 'Closed')], default=1, max_length=6),
        ),
    ]
