# Generated by Django 4.0.4 on 2022-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6),
        ),
    ]
